#!/bin/bash
alias c="clear"
alias ca="printf '\033c'"
alias cd-stockanalysis2="cd /Users/michaelstecklein/Projects/StockAnalysis2/"
alias cd-securitycamera="cd /Users/michaelstecklein/Projects/beagleboneblack/securitycamera"
alias cd-mysql-mac="cd /usr/local/var/mysql"
alias cd-motiondetection="cd /Users/michaelstecklein/Projects/MotionDetection"
alias gitl="git log --oneline"
alias gits="git status"
alias mysql="mysql -u root -p"
